In [1]:
import pandas as pd

In [2]:
data = {
    'student': ['Amit','John','Jacob','David','Steve'],
    'rank': [1,4,3,2,5],
    'marks':[95,70,80,60,90]
}

df = pd.DataFrame(data)

In [3]:
df

  student  rank  marks
0    Amit     1     95
1    John     4     70
2   Jacob     3     80
3   David     2     60
4   Steve     5     90

## Custome Indexes

In [4]:
custom_index = pd.DataFrame(data, index = ['Student-1', 'Student-2', 'Student-3', 'Student-4', 'Student-5'])
custom_index

          student  rank  marks
Student-1    Amit     1     95
Student-2    John     4     70
Student-3   Jacob     3     80
Student-4   David     2     60
Student-5   Steve     5     90

In [5]:
custom_index.iloc[[1, 2]]

          student  rank  marks
Student-2    John     4     70
Student-3   Jacob     3     80

In [6]:
custom_index.loc[('Student-3', 'marks')]

np.int64(80)

# Iterating the dataframe columns

In [7]:
for col in custom_index:
    print(col)

student
rank
marks

# Pandas attributes and methods
words without parenthesis are called properties like variables they have values stored in them and are printed upon usage <br>
words with parenthesis are called methods they are called like a function which returns the customized data about the data which being asked

    .dtypes
    .ndim
    .size
    .shape
    .index
    .T or .transpose()
    .head()
    .tail()

In [8]:
print(df.dtypes)

student      str
rank       int64
marks      int64
dtype: object

In [9]:
# using the following we can see the number of dimensions of the dataframe

print(df.ndim)

2

In [10]:
# to get the number of elements in the dataframe

df.size

15

In [11]:
# to get the dimensions in tapul form use .shape attribute
df.shape

(5, 3)

## Index attribute

In [12]:
print(df.index)
print(custom_index.index)
# it the index is in a range it will return range or else it will return the sep indicies

RangeIndex(start=0, stop=5, step=1)
Index(['Student-1', 'Student-2', 'Student-3', 'Student-4', 'Student-5'], dtype='str')

## Transpose rows and cols

In [13]:
print("Transpose of the table is:\n\n", custom_index.T)
print("\n", custom_index.T.equals(custom_index.transpose()))

Transpose of the table is:

         Student-1 Student-2 Student-3 Student-4 Student-5
student      Amit      John     Jacob     David     Steve
rank            1         4         3         2         5
marks          95        70        80        60        90

 True

In [14]:
## .head() method

(custom_index.head(2))

          student  rank  marks
Student-1    Amit     1     95
Student-2    John     4     70

In [15]:
(custom_index.tail(2))

          student  rank  marks
Student-4   David     2     60
Student-5   Steve     5     90

# Joining Pandas Dataframs

In [16]:
data1 = {
    "id":["S01","S02","S03","S04","S05"],
    'Student':['Amit','John','Jacob','David','Steve'],
    'Roll':[101, 102, 103, 104, 105]
}

data2 = {
    'Rank':[1,4,3,5],
    'Marks':[95,70,80,60]
}

In [17]:
dataFrame1 = pd.DataFrame(data1)
dataFrame2 = pd.DataFrame(data2)

print("dataFrame1 =\n",dataFrame1)
print("\n\n")
print("dataFrame2 =\n",dataFrame2)

dataFrame1 =
     id Student  Roll
0  S01    Amit   101
1  S02    John   102
2  S03   Jacob   103
3  S04   David   104
4  S05   Steve   105



dataFrame2 =
    Rank  Marks
0     1     95
1     4     70
2     3     80
3     5     60

In [18]:
# Joining the dataframe

resultant = dataFrame1.join(dataFrame2) # the dataframe 1 will have all the values but data frame 2 will loose or miss values as per the first dataframe

In [19]:
resultant

    id Student  Roll  Rank  Marks
0  S01    Amit   101   1.0   95.0
1  S02    John   102   4.0   70.0
2  S03   Jacob   103   3.0   80.0
3  S04   David   104   5.0   60.0
4  S05   Steve   105   NaN    NaN

# Concatenating dataframes

In [20]:
concat1 = {
    "id":["S01","S02","S03","S04","S05"],
    'Student':['Amit','John','Jacob','David','Steve'],
    'Roll':[101, 102, 103, 104, 105]
}

In [21]:
concat2 = {
    'id':['S06','S07','S08'],
    'Student':['Benjamin','Isabella','Jacob'],
}

In [22]:
concat1df = pd.DataFrame(concat1, index = ['Student-1', 'Student-2', 'Student-3','Student-4','Student-5'])
concat2df = pd.DataFrame(concat2, index= ['Student-6', 'Student-7', 'Student-8'])
concat_result = pd.concat([concat1df, concat2df], ignore_index=True)

In [23]:
concat_result

    id   Student   Roll
0  S01      Amit  101.0
1  S02      John  102.0
2  S03     Jacob  103.0
3  S04     David  104.0
4  S05     Steve  105.0
5  S06  Benjamin    NaN
6  S07  Isabella    NaN
7  S08     Jacob    NaN

In [24]:
concat_result.iloc[6,1]

'Isabella'

# Series

In [25]:
import numpy as np
data_list = [10,20,30,40,np.nan]

Series_eg = pd.Series(data_list,name='Numbers')

Series_eg2 = pd.Series(data_list,name='Numbers', index = ['One','Two','Three','Four','Five'])

In [26]:
## Accessing a values from the series

print(Series_eg[4])
print("\n")
print(Series_eg[:4])
print("\n")
print(Series_eg[1:2])

nan


0    10.0
1    20.0
2    30.0
3    40.0
Name: Numbers, dtype: float64


1    20.0
Name: Numbers, dtype: float64

Accessing lables from the Series

In [27]:
print(Series_eg2.loc['Five'])
print('\n')
print(Series_eg2.iloc[3])

nan


40.0

Series Attributes

    .dtype
    .ndim
    .size
    .name
    .hasnans
    .index
    .head
    .tail
    .info

In [28]:
Series_eg2.name

'Numbers'

In [29]:
Series_eg2.ndim

1

In [30]:

Series_eg.hasnans

True

In [31]:
Series_eg2.info()

<class 'pandas.Series'>
Index: 5 entries, One to Five
Series name: Numbers
Non-Null Count  Dtype
--------------  -----
4 non-null      float64
dtypes: float64(1)
memory usage: 252.0+ bytes

In [32]:
Series_eg.size

5

In [33]:
Series_eg.shape

(5,)

In [34]:
Series_eg2.index

Index(['One', 'Two', 'Three', 'Four', 'Five'], dtype='str')

# Combining two series

In [35]:
Series1 = pd.Series([10,20,40,80,100])
Series2 = pd.Series([25,5,75,95,45])

In [36]:
def demo(x1,x2):
    if (x1 > x2):
        return x1
    else:
        return x2

In [37]:
combine_series = Series1.combine(Series2,demo) # Combining means it compares and keeps the value based on the function condition

In [38]:
combine_series

0     25
1     20
2     75
3     95
4    100
dtype: int64

In [39]:
combine_using_lambda = Series1.combine(Series2, lambda x1,x2: max(x1,x2))
combine_using_lambda

0     25
1     20
2     75
3     95
4    100
dtype: int64

# Concatenating Series

In [40]:
Series_concat = pd.concat([Series1,Series2], ignore_index=True)
Series_concat

0     10
1     20
2     40
3     80
4    100
5     25
6      5
7     75
8     95
9     45
dtype: int64