In [14]:
import pandas as pd
import numpy as np

In [2]:
data = {
    'Id':['S01','S02','S03','S04','S05'],
    'Student':['Rohit','Steve','Virat','Virat','Rohit'],
    'Rank':[1,4,3,5,2],
    'Marks':[95,70,80,60,90]

}

In [3]:
df = pd.DataFrame(data)

In [4]:
#To print the first occurance of each entry
first_non_null_entries = df.groupby('Student').first()
first_non_null_entries

          Id  Rank  Marks
Student
Rohit    S01     1     95
Steve    S02     4     70
Virat    S03     3     80

### Iterating the Group

In [5]:
grp = df.groupby('Student')

In [6]:
for name, group in grp:
    print(name,'\n',group,'\n')

Rohit
     Id Student  Rank  Marks
0  S01   Rohit     1     95
4  S05   Rohit     2     90

Steve
     Id Student  Rank  Marks
1  S02   Steve     4     70

Virat
     Id Student  Rank  Marks
2  S03   Virat     3     80
3  S04   Virat     5     60

### View the group using Groups method

In [7]:
df

    Id Student  Rank  Marks
0  S01   Rohit     1     95
1  S02   Steve     4     70
2  S03   Virat     3     80
3  S04   Virat     5     60
4  S05   Rohit     2     90

In [8]:
grp.groups

{'Rohit': [0, 4], 'Steve': [1], 'Virat': [2, 3]}

### applying aggregations on the groups

In [9]:
mean = df.groupby('Student')['Marks'].mean()
mean

Student
Rohit    92.5
Steve    70.0
Virat    70.0
Name: Marks, dtype: float64

In [10]:
players = {
    'Player':["Amit","John","Amit","David","Kane","John"],
    'Points':[95,98,92,99,94,91],
    "Year":[2011,2015,2011,2019,2015,2019]
}

In [11]:
player_df = pd.DataFrame(data=players)

##### Creating Groups

In [12]:
points_per_year = player_df.groupby(['Year','Player'])

##### Aggregation on the groups

In [20]:
points_per_year['Points'].sum()

Year  Player
2011  Amit      187
2015  John       98
      Kane       94
2019  David      99
      John       91
Name: Points, dtype: int64

### Using Numpy with Grouby

In [16]:
points_per_year['Points'].agg(np.mean)

Year  Player
2011  Amit      93.5
2015  John      98.0
      Kane      94.0
2019  David     99.0
      John      91.0
Name: Points, dtype: float64

### Preview the size of the Groups

In [17]:
points_per_year['Points'].agg(np.size)

Year  Player
2011  Amit      2
2015  John      1
      Kane      1
2019  David     1
      John      1
Name: Points, dtype: int64