In [1]:
import pandas as pd
customers = pd.read_csv("/Volumes/Projects/wip-Projects/customer.csv")

In [2]:
customers.head()

,Customer Name,Address,Amount,Transaction Date,Type
0,John Doe,123 Main St; Anytown; USA,347.89,03-15-2024,Groceries
1,Jane Smith,456 Elm St; Anycity; USA,671.25,07-22-2024,Home Goods
2,Michael Johnson,101 Pine St; Anyvillage; USA,492.73,09-11-2024,Travel
3,Emily Brown,202 Maple St; Anyborough; USA,756.84,05-09-2024,Travel
4,William Davis,789 Oak St; Anystate; USA,125.61,11-28-2024,Electronics

In [3]:
customers.tail(2)

,Customer Name,Address,Amount,Transaction Date,Type
62,Michael Johnson,789 Oak St; Anystate; USA,224.01,12-11-2024,Home Goods
63,Emily Brown,456 Elm St; Anycity; USA,797.62,06-28-2024,Travel

In [4]:
customers['Amount'].sum().round(9)

np.float64(30093.44)

# Reading Excel File

In [5]:
Players = pd.read_excel('/Volumes/Projects/Datasets/Players.xlsx', index_col=0, header = 0)
Players

        Rank  Point
Player
Virat      1    100
David      2     95
Steve      3     85
Ben        4     70
Rohit      5     65
Kane       6     60

In [6]:
Player_excel = pd.read_excel('/Volumes/Projects/Datasets/Players.xlsx')
Player_excel

  Player  Rank  Point
0  Virat     1    100
1  David     2     95
2  Steve     3     85
3    Ben     4     70
4  Rohit     5     65
5   Kane     6     60

# Pandas Indexing

In [7]:
print("Captain of Indian Cricket Team is",'`',Player_excel.iloc[0,0],'`')
Player_excel.loc[[1,4]] # to print custom rows, say 1st and 4th

Captain of Indian Cricket Team is ` Virat `

  Player  Rank  Point
1  David     2     95
4  Rohit     5     65

### Selecting two columns

In [8]:
# Printing only the Points and names

print(Player_excel[['Player','Point']])
print(type(Player_excel[['Player','Point']]))

  Player  Point
0  Virat    100
1  David     95
2  Steve     85
3    Ben     70
4  Rohit     65
5   Kane     60
<class 'pandas.DataFrame'>

In [9]:
print(Player_excel.iloc[0])

Player    Virat
Rank          1
Point       100
Name: 0, dtype: object

### Multiple cols in a range

In [10]:
# syntax DataFrame[DataFrame.columnd[x:y]
print(customers.columns)
customers[customers.columns[0:5:2]].head(3)

Index(['Customer Name', 'Address', 'Amount', 'Transaction Date', 'Type'], dtype='str')

     Customer Name  Amount        Type
0         John Doe  347.89   Groceries
1       Jane Smith  671.25  Home Goods
2  Michael Johnson  492.73      Travel

### Adding new columns in dataframe

In [11]:
data = {
    'Id':['S01','S02','S03','S04','S05'],
    'Student':['Amit','Steve','John','Virat','Rohit'],
    'Rank':[1,4,3,5,2],
    'Marks':[95,70,80,60,90]

}

In [12]:
DF  = pd.DataFrame(data)

In [13]:
DF.insert(1,"Roll_Number",[101,102,103,104,105])
DF

    Id  Roll_Number Student  Rank  Marks
0  S01          101    Amit     1     95
1  S02          102   Steve     4     70
2  S03          103    John     3     80
3  S04          104   Virat     5     60
4  S05          105   Rohit     2     90

In [14]:
DF.drop(columns = ["Roll_Number"], inplace=True,errors="ignore")

### AddinUsing assign function

In [15]:
DF = DF.assign(Roll = ['1','2','3','4','5'])
DF['ROLLNEW'] = ['10','20','30','40','50']

In [16]:
DF = DF.assign(Delete = ['d','d','d','d','d'])

In [17]:
DF

    Id Student  Rank  Marks Roll ROLLNEW Delete
0  S01    Amit     1     95    1      10      d
1  S02   Steve     4     70    2      20      d
2  S03    John     3     80    3      30      d
3  S04   Virat     5     60    4      40      d
4  S05   Rohit     2     90    5      50      d

#### Drop a column

    three ways of removing a column
    Using .drop(columns = ['Col1','Col2])
    Using .drop(['ColName','ColName2'], asis = column
    Uding .drop(['ColName','ColName2'], axis = 1)  # 1 stands for axis

In [18]:
DF.drop(columns = ['ROLLNEW'],inplace = True,errors="ignore")

In [19]:
DF.drop(['Roll'], inplace = True,errors="ignore", axis = 'columns')

In [20]:
DF.drop('Delete', inplace = True, errors="ignore", axis = 1)

In [21]:
DF

    Id Student  Rank  Marks
0  S01    Amit     1     95
1  S02   Steve     4     70
2  S03    John     3     80
3  S04   Virat     5     60
4  S05   Rohit     2     90

### To remove an index, i.e a row
    using axis = 0 or axis = 'index'

In [22]:
DF.drop([1,2],errors = "ignore", inplace = True, axis = 0)

In [27]:
DF.drop(0, errors = "ignore", axis = 'index', inplace = True)
DF

    Id Student  Rank  Marks
3  S04   Virat     5     60
4  S05   Rohit     2     90