In [1]:
import pandas as pd

In [3]:
df = pd.read_csv("Null.csv")

In [4]:
df

   Frequency   Points
0        2.4     83.5
1        3.2     21.6
2        6.1      NaN
3        1.2     45.9
4        3.8     23.3
5        4.5      NaN
6        8.3     66.3
7        7.9     74.7
8        5.8     67.5

In [13]:
df.notnull()

   Frequency   Points
0       True     True
1       True     True
2       True    False
3       True     True
4       True     True
5       True    False
6       True     True
7       True     True
8       True     True

In [8]:
df.isnull()

   Frequency   Points
0      False    False
1      False    False
2      False     True
3      False    False
4      False    False
5      False     True
6      False    False
7      False    False
8      False    False

In [21]:
drop_na = df.dropna()

In [22]:
drop_na

   Frequency   Points
0        2.4     83.5
1        3.2     21.6
3        1.2     45.9
4        3.8     23.3
6        8.3     66.3
7        7.9     74.7
8        5.8     67.5

In [25]:
fill_na = df.fillna('Filled_val')
fill_na

   Frequency      Points
0        2.4        83.5
1        3.2        21.6
2        6.1  Filled_val
3        1.2        45.9
4        3.8        23.3
5        4.5  Filled_val
6        8.3        66.3
7        7.9        74.7
8        5.8        67.5