In [2]:
import pandas as pd

In [6]:
data_dictionary = [
    {"field_name": "user_id", "description": "Unique identifier for a user", "data_type": "Integer", "example": 1001, "source": "User Database"},
    {"field_name": "name", "description": "Full name of the user", "data_type": "String", "example": "John Doe", "source": "User Input"},
    {"field_name": "user_id", "description": "Unique identifier for a user", "data_type": "Integer", "example": 1001, "source": "User Database"},
    {"field_name": "email", "description": "User's email address", "data_type": "String", "example": "john@example.com", "source": "User Input"},
    {"field_name": "name", "description": "Full name of the user", "data_type": "String", "example": "John Doe", "source": "User Input"},
    {"field_name": "age", "description": "Age of the user", "data_type": "Integer", "example": 30, "source": "User Input"},
    {"field_name": "email", "description": "User's email address", "data_type": "String", "example": "john@example.com", "source": "User Input"}
]

In [7]:
df = pd.DataFrame(data_dictionary)
df

,field_name,description,data_type,example,source
0,user_id,Unique identifier for a user,Integer,1001,User Database
1,name,Full name of the user,String,John Doe,User Input
2,user_id,Unique identifier for a user,Integer,1001,User Database
3,email,User's email address,String,john@example.com,User Input
4,name,Full name of the user,String,John Doe,User Input
5,age,Age of the user,Integer,30,User Input
6,email,User's email address,String,john@example.com,User Input

In [8]:
df.duplicated()

0    False
1    False
2     True
3    False
4     True
5    False
6     True
dtype: bool

In [9]:
df.drop_duplicates()

,field_name,description,data_type,example,source
0,user_id,Unique identifier for a user,Integer,1001,User Database
1,name,Full name of the user,String,John Doe,User Input
3,email,User's email address,String,john@example.com,User Input
5,age,Age of the user,Integer,30,User Input

In [3]:
print(pd.__version__)

3.0.3